site_name: PDF2Ca$h
nav:
  - Home: index.md
  - DevOps: 
    - GitFlow: devops/gitflow.md
    - Politica de Issues: devops/issue-policy.md
  - Metodologia:
    - Backlog: methodology/backlog.md
    - Riscos: methodology/risks.md
    - Sprints:
      - Sprint 1: methodology/sprints/SPRINT1.md
      - Sprint 2: methodology/sprints/SPRINT2.md
      - Sprint 3: methodology/sprints/SPRINT3.MD
      - Sprint 4: methodology/sprints/SPRINT4.MD
      - Sprint 5: methodology/sprints/SPRINT5.md
      - Sprint 6: methodology/sprints/SPRINT6.md
      - Sprint 7: methodology/sprints/SPRINT7.md
      - Sprint 8: methodology/sprints/SPRINT8.md
      - Sprint 9: methodology/sprints/SPRINT9.md
      - Sprint 10: methodology/sprints/SPRINT10.md
      - Sprint 11: methodology/sprints/SPRINT11.md
      - Sprint 12: methodology/sprints/SPRINT12.md
      - Sprint 13: methodology/sprints/SPRINT13.md
  - Gerencia de projeto:
    - Canvas: project-management/canvas.md
    - EAP: project-management/eap.md
    - TAP: project-management/tap.md
  - Casos de uso: casos-de-uso.md
  - Codigo de conduta: CODE_OF_CONDUCT.md
  - Politica de contribuição: index.md
  - Especificação suplementar: documento-de-especificacao-suplementar.md
  - Roadmaps:
    - Geral: GENERAL_ROADMAP.md
    - Por papel: ROLE_ROADMAP.md
  - Licença: LICENSE.md
  - Documento de visão: vision-document.md

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'blue'

markdown_extensions:
- codehilite
